### PR TITLE
Speed sensitive volume

### PR DESCRIPTION
**Pull request by lau85**
I think it is "must have" feature. Wondering why it is not included as standard.
Wrote it yesterday and only tested today on a single ride. Volume formula can be improved as everything else in this script. Use at your own risk.

### CODE REVIEW

**Comment by jnuyens** [comment]
This is a great addition, indeed! Also, your code is very nice and gives some illustrations to optimise the existing stuff! Thanks a lot!

**Comment by ramonsmits** [comment]
Can you explain the math and behavior behind this? Trying to understand when the functions are called and how it calculates the right value which also depends on the configured volume level.

Does this mean that the UI volume level is fixed and is a different value?

**Comment by lau85** [comment]
It reads vehicle speed and volume when script is started. We will have it
as INIT_SPEED and INIT_VOLUME for later. Also PREV_VOLUME(previous) is set
to the same value as INIT_VOLUME.
Then every second it does:
   If volume have been changed from GUI. (CURRENT_VOLUME is different from
PREV_VOLUME) it updates INIT_SPEED and INIT_VOLUME to current values.
   If volume is the same (no changes from GUI), but speed is different,
increases/decreases volume using formula
NEW_SPEED = INIT_SPEED + (0.333 * (CURRENT_SPEED - INIT_SPEED)/10000).
10000 there is for 10 miles/h.

Made 200 km today. I can say that the script is working pretty well. There
was only one situation when volume was increased unexpectedly. Apart from
that single case, I couldn't really if it is working at all. :)

**Comment by lau85** [comment]
sorry, should be 
NEW_VOLUME = INIT_VOLUME + (0.333 * (CURRENT_SPEED - INIT_SPEED)/10000).

**Comment by ramonsmits** [comment]
Ok, I think I understand but you would see the volume indicator to slightly up/down right?

What happens when you adjust the volume on the highway? Lets see I turn the volume down on the highway and then slow down. Would this slightly keep decreasing the actual volume too?

I see it is a while loop and seems to adjust every second right? I'm not familiar with this scripting language.

**Comment by ramonsmits** [comment]
By the way, instead of adding .333 should this be a multiplication as I think volume due to wind noise being exponential?

**Comment by lau85** [comment]
If you change volume on high speed, it updates unit values and will lower
it automatically if you slow down. For now it is linear. And only tested on
Model S 2013 with premium audio. Need to do more real life testing. As
always, time is an issue.

**Comment by jnuyens** [comment]
I'm also testing on my Model X, fixed some minor issues, it seems to work very nice :) Saturday, we have a 11 hour drive across EU ahead, so plenty of testing opportunities at highway speeds.

**Pull request merged**
